"""Initial database schema

Revision ID: cc75d2899726
Revises: 
Create Date: 2025-11-18 14:47:10.238068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc75d2899726'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_taxonomy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_class', sa.String(length=100), nullable=False, comment='Top-level class (Equity, Fixed_Income, etc.)'),
    sa.Column('asset_subclass', sa.String(length=100), nullable=True, comment='Sub-category within class'),
    sa.Column('display_name', sa.String(length=200), nullable=True, comment='User-friendly name'),
    sa.Column('target_allocation', sa.Numeric(precision=5, scale=2), nullable=True, comment='Target allocation percentage (0-100)'),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='Low, Medium, High'),
    sa.Column('benchmark_index', sa.String(length=100), nullable=True, comment='Benchmark for performance comparison'),
    sa.Column('parent_class', sa.String(length=100), nullable=True, comment='Parent class for nested hierarchies'),
    sa.Column('metadata_json', sa.JSON(), nullable=True, comment='Additional configuration'),
    sa.Column('version', sa.Integer(), nullable=True, comment='Config version for rollback'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='False if deprecated'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_class', 'asset_subclass', 'version', name='uq_taxonomy_version')
    )
    op.create_table('assets',
    sa.Column('asset_id', sa.String(length=100), nullable=False, comment='Standardized asset identifier'),
    sa.Column('asset_name', sa.String(length=200), nullable=False, comment='Display name'),
    sa.Column('asset_type', sa.String(length=100), nullable=True, comment='Fund, ETF, Stock, RSU, Insurance, etc.'),
    sa.Column('asset_class', sa.String(length=100), nullable=True, comment='Equity, Fixed_Income, Alternative, etc.'),
    sa.Column('asset_subclass', sa.String(length=100), nullable=True, comment='Sub-category within asset class'),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='Low, Medium, High'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='False if asset no longer held'),
    sa.Column('metadata_json', sa.JSON(), nullable=True, comment='Asset-specific fields (fund codes, tickers, etc.)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('audit_trail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=True, comment='User or system component'),
    sa.Column('action', sa.String(length=50), nullable=True, comment='INSERT, UPDATE, DELETE, IMPORT, ROLLBACK'),
    sa.Column('table_name', sa.String(length=100), nullable=True, comment='Table that was modified'),
    sa.Column('record_id', sa.String(length=100), nullable=True, comment='Primary key of modified record'),
    sa.Column('old_value', sa.JSON(), nullable=True, comment='Record state before change'),
    sa.Column('new_value', sa.JSON(), nullable=True, comment='Record state after change'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Why this change was made'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.create_index('idx_audit_timestamp_table', ['timestamp', 'table_name'], unique=False)
        batch_op.create_index('idx_audit_user_action', ['user', 'action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_trail_table_name'), ['table_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_trail_timestamp'), ['timestamp'], unique=False)

    op.create_table('backup_manifest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backup_date', sa.DateTime(), nullable=False),
    sa.Column('backup_file', sa.String(length=200), nullable=False, comment='Backup filename'),
    sa.Column('backup_type', sa.String(length=20), nullable=True, comment='Full or Incremental'),
    sa.Column('file_size_mb', sa.Numeric(precision=10, scale=2), nullable=True, comment='Backup file size in MB'),
    sa.Column('checksum', sa.String(length=64), nullable=True, comment='SHA256 hash for integrity verification'),
    sa.Column('is_verified', sa.Boolean(), nullable=True, comment='True if restore test passed'),
    sa.Column('retention_until', sa.Date(), nullable=True, comment='Delete backup after this date'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional backup notes'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_manifest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_manifest_backup_date'), ['backup_date'], unique=False)

    op.create_table('balance_sheets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False, comment='Date of snapshot'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Asset, Liability, or Equity'),
    sa.Column('subcategory', sa.String(length=100), nullable=True, comment='Cash, Investments, Debt, etc.'),
    sa.Column('line_item', sa.String(length=200), nullable=True, comment='Specific item name'),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True, comment='Amount in specified currency'),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional notes or context'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('balance_sheets', schema=None) as batch_op:
        batch_op.create_index('idx_balance_sheet_date_category', ['snapshot_date', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_balance_sheets_snapshot_date'), ['snapshot_date'], unique=False)

    op.create_table('benchmarks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('benchmark_name', sa.String(length=100), nullable=False, comment='Unique benchmark name'),
    sa.Column('benchmark_type', sa.String(length=50), nullable=True, comment='Index or Custom'),
    sa.Column('ticker_symbol', sa.String(length=20), nullable=True, comment='Ticker for standard indices'),
    sa.Column('composition', sa.JSON(), nullable=True, comment='Dict of {ticker: weight} for custom benchmarks'),
    sa.Column('data_source', sa.String(length=50), nullable=True, comment='Yahoo, Manual, Calculated, etc.'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='False if no longer used'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('benchmark_name')
    )
    op.create_table('config_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_table', sa.String(length=100), nullable=True, comment='Which config table was changed'),
    sa.Column('config_id', sa.Integer(), nullable=True, comment='Primary key of the config record'),
    sa.Column('change_date', sa.DateTime(), nullable=False),
    sa.Column('changed_by', sa.String(length=50), nullable=True),
    sa.Column('change_type', sa.String(length=20), nullable=True, comment='CREATE, UPDATE, or DELETE'),
    sa.Column('snapshot', sa.JSON(), nullable=True, comment='Full config state at this version'),
    sa.Column('change_reason', sa.Text(), nullable=True, comment='Why this change was made'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('config_history', schema=None) as batch_op:
        batch_op.create_index('idx_config_history_table_date', ['config_table', 'change_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_history_change_date'), ['change_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_history_config_table'), ['config_table'], unique=False)

    op.create_table('import_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('source_file', sa.String(length=200), nullable=True, comment='Original filename'),
    sa.Column('source_type', sa.String(length=50), nullable=True, comment='Excel, CSV, API'),
    sa.Column('records_imported', sa.Integer(), nullable=True, comment='Successfully imported'),
    sa.Column('records_updated', sa.Integer(), nullable=True, comment='Updated existing records'),
    sa.Column('records_failed', sa.Integer(), nullable=True, comment='Failed validation'),
    sa.Column('error_log', sa.Text(), nullable=True, comment='Error messages and stack traces'),
    sa.Column('imported_by', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True, comment='Success, Partial, or Failed'),
    sa.Column('can_rollback', sa.Boolean(), nullable=True, comment="False if data can't be undone"),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_log_import_date'), ['import_date'], unique=False)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False, comment='Unique setting identifier'),
    sa.Column('setting_value', sa.Text(), nullable=True, comment='Setting value (JSON string for complex values)'),
    sa.Column('setting_type', sa.String(length=50), nullable=True, comment='string, integer, json, boolean, etc.'),
    sa.Column('description', sa.Text(), nullable=True, comment='What this setting controls'),
    sa.Column('version', sa.Integer(), nullable=True, comment='Setting version for rollback'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_setting_key'), ['setting_key'], unique=True)

    op.create_table('asset_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=100), nullable=True, comment='Explicit asset ID'),
    sa.Column('asset_name_pattern', sa.String(length=200), nullable=True, comment='Pattern for fuzzy matching'),
    sa.Column('asset_class', sa.String(length=100), nullable=False, comment='Target asset class'),
    sa.Column('asset_subclass', sa.String(length=100), nullable=True, comment='Target sub-class'),
    sa.Column('mapping_type', sa.String(length=50), nullable=True, comment='Explicit, Pattern, or Manual'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='Higher priority wins in conflicts'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='False if disabled'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False, comment='Date of this snapshot'),
    sa.Column('asset_id', sa.String(length=100), nullable=False),
    sa.Column('asset_name', sa.String(length=200), nullable=False, comment='Display name'),
    sa.Column('shares', sa.Numeric(precision=18, scale=6), nullable=True, comment='Number of shares held'),
    sa.Column('current_price', sa.Numeric(precision=18, scale=6), nullable=True, comment='Price per share at snapshot date'),
    sa.Column('market_value', sa.Numeric(precision=18, scale=2), nullable=True, comment='Total market value (shares * price)'),
    sa.Column('cost_basis', sa.Numeric(precision=18, scale=2), nullable=True, comment='Total cost basis (FIFO/LIFO)'),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=2), nullable=True, comment='Unrealized profit/loss'),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'asset_id', name='uq_holding_snapshot')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index('idx_holdings_date_asset', ['snapshot_date', 'asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holdings_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holdings_snapshot_date'), ['snapshot_date'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False, comment='Generated hash for deduplication'),
    sa.Column('date', sa.Date(), nullable=False, comment='Transaction date'),
    sa.Column('asset_id', sa.String(length=100), nullable=False),
    sa.Column('asset_name', sa.String(length=200), nullable=False, comment='Display name'),
    sa.Column('transaction_type', sa.String(length=50), nullable=False, comment='Buy, Sell, Dividend_Cash, etc.'),
    sa.Column('shares', sa.Numeric(precision=18, scale=6), nullable=True, comment='Number of shares (NULL for cash-only transactions)'),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=True, comment='Price per share (NULL for cash-only)'),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='Total transaction amount'),
    sa.Column('currency', sa.String(length=10), nullable=True, comment='Transaction currency'),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=6), nullable=True, comment='Exchange rate to CNY if not CNY'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='CN_Fund, Schwab, Manual_Excel, etc.'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='User or system component'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_transactions_date_asset', ['date', 'asset_id'], unique=False)
        batch_op.create_index('idx_transactions_type_date', ['transaction_type', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_id'), ['transaction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_type'), ['transaction_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_asset_id'))
        batch_op.drop_index('idx_transactions_type_date')
        batch_op.drop_index('idx_transactions_date_asset')

    op.drop_table('transactions')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_holdings_asset_id'))
        batch_op.drop_index('idx_holdings_date_asset')

    op.drop_table('holdings')
    op.drop_table('asset_mappings')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_setting_key'))

    op.drop_table('system_settings')
    with op.batch_alter_table('import_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_log_import_date'))

    op.drop_table('import_log')
    with op.batch_alter_table('config_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_history_config_table'))
        batch_op.drop_index(batch_op.f('ix_config_history_change_date'))
        batch_op.drop_index('idx_config_history_table_date')

    op.drop_table('config_history')
    op.drop_table('benchmarks')
    with op.batch_alter_table('balance_sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_sheets_snapshot_date'))
        batch_op.drop_index('idx_balance_sheet_date_category')

    op.drop_table('balance_sheets')
    with op.batch_alter_table('backup_manifest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_manifest_backup_date'))

    op.drop_table('backup_manifest')
    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_trail_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_trail_table_name'))
        batch_op.drop_index('idx_audit_user_action')
        batch_op.drop_index('idx_audit_timestamp_table')

    op.drop_table('audit_trail')
    op.drop_table('assets')
    op.drop_table('asset_taxonomy')
    # ### end Alembic commands ###
