"""Phase 6.2: Add MonthlyFinancialSnapshot, InsurancePremium, MarketDataNAV tables

Revision ID: e27a2521e412
Revises: cc75d2899726
Create Date: 2025-11-22 15:53:48.963700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e27a2521e412'
down_revision: Union[str, None] = 'cc75d2899726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_premiums',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_id', sa.String(length=100), nullable=False, comment='Policy identifier'),
    sa.Column('policy_name', sa.String(length=200), nullable=False, comment='Policy display name'),
    sa.Column('insurer', sa.String(length=100), nullable=True, comment='Insurance company name'),
    sa.Column('payment_date', sa.Date(), nullable=False, comment='Date premium was paid'),
    sa.Column('premium_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='Premium payment amount'),
    sa.Column('payment_frequency', sa.String(length=20), nullable=True, comment='Annual, Semi-Annual, Monthly, etc.'),
    sa.Column('coverage_start', sa.Date(), nullable=True, comment='Policy coverage start date'),
    sa.Column('coverage_end', sa.Date(), nullable=True, comment='Policy coverage end date'),
    sa.Column('insured_person', sa.String(length=100), nullable=True, comment='Name of insured person'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Payment notes or special terms'),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurance_premiums', schema=None) as batch_op:
        batch_op.create_index('idx_insurance_premiums_date_policy', ['payment_date', 'policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurance_premiums_payment_date'), ['payment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurance_premiums_policy_id'), ['policy_id'], unique=False)

    op.create_table('market_data_nav',
    sa.Column('asset_id', sa.String(length=100), nullable=False, comment='Asset identifier (fund code)'),
    sa.Column('date', sa.Date(), nullable=False, comment='NAV date'),
    sa.Column('nav', sa.Numeric(precision=18, scale=6), nullable=False, comment='Net Asset Value per unit'),
    sa.Column('accumulated_nav', sa.Numeric(precision=18, scale=6), nullable=True, comment='Accumulated NAV (includes dividends)'),
    sa.Column('daily_growth_rate', sa.Numeric(precision=8, scale=4), nullable=True, comment='Daily growth rate percentage'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='Data source (API name, manual, etc.)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('asset_id', 'date')
    )
    with op.batch_alter_table('market_data_nav', schema=None) as batch_op:
        batch_op.create_index('idx_market_data_nav_asset_date', ['asset_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_data_nav_date'), ['date'], unique=False)

    op.create_table('monthly_financial_snapshots',
    sa.Column('snapshot_date', sa.Date(), nullable=False, comment='Month end date (e.g., 2025-11-30)'),
    sa.Column('salary_income', sa.Numeric(precision=18, scale=2), nullable=True, comment='Monthly salary/wages'),
    sa.Column('rsu_income', sa.Numeric(precision=18, scale=2), nullable=True, comment='RSU vesting income'),
    sa.Column('investment_income', sa.Numeric(precision=18, scale=2), nullable=True, comment='Dividends, interest, realized gains'),
    sa.Column('other_income', sa.Numeric(precision=18, scale=2), nullable=True, comment='Other income sources'),
    sa.Column('total_income', sa.Numeric(precision=18, scale=2), nullable=False, comment='Sum of all income'),
    sa.Column('housing_expense', sa.Numeric(precision=18, scale=2), nullable=True, comment='Rent/mortgage, utilities'),
    sa.Column('living_expense', sa.Numeric(precision=18, scale=2), nullable=True, comment='Food, transportation, daily expenses'),
    sa.Column('healthcare_expense', sa.Numeric(precision=18, scale=2), nullable=True, comment='Medical, insurance premiums'),
    sa.Column('entertainment_expense', sa.Numeric(precision=18, scale=2), nullable=True, comment='Travel, hobbies, dining out'),
    sa.Column('investment_expense', sa.Numeric(precision=18, scale=2), nullable=True, comment='Investment purchases (not counted in savings)'),
    sa.Column('other_expense', sa.Numeric(precision=18, scale=2), nullable=True, comment='Other expenses'),
    sa.Column('total_expense', sa.Numeric(precision=18, scale=2), nullable=False, comment='Sum of all expenses'),
    sa.Column('net_savings', sa.Numeric(precision=18, scale=2), nullable=True, comment='Total income - Total expense'),
    sa.Column('savings_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='Savings rate percentage (0-100)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Month commentary or special events'),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('snapshot_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_financial_snapshots')
    with op.batch_alter_table('market_data_nav', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_data_nav_date'))
        batch_op.drop_index('idx_market_data_nav_asset_date')

    op.drop_table('market_data_nav')
    with op.batch_alter_table('insurance_premiums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurance_premiums_policy_id'))
        batch_op.drop_index(batch_op.f('ix_insurance_premiums_payment_date'))
        batch_op.drop_index('idx_insurance_premiums_date_policy')

    op.drop_table('insurance_premiums')
    # ### end Alembic commands ###
